### ISSUE TITLE
sharing failed when sending video to WeChat and Line

### ISSUE THREAD

**Issue by SzuWeiChen** [yasirkula/UnityNativeShare#1]
sharing failed when sending video to WeChat and Line

**Comment by yasirkula** [comment]
Can you also try it on another phone? If that doesn't work, can you post the device logs (logcat) here?

**Comment by SzuWeiChen** [comment]
it is my test project and apk
https://drive.google.com/drive/folders/0B07cVkP6fZfVdnk4aHZURy0zTk0?usp=sharing

I can share it to facebook and youtube
but sharing failed when sending to WeChat and Line

**Comment by yasirkula** [comment]
I honestly am clueless about the fix to this bug right now. The source code of FileProvider is almost the same as Android's official FileProvider (android.support.v4.content.FileProvider). It was mostly a copy-paste anyways. I couldn't spot any potential flaws in the code yet.

Also, sorry for the late response. And thank you for sharing the test project.

**Comment by yasirkula** [comment]
I've recently googled this issue and found the following entries:

https://github.com/tvbarthel/IntentShare/issues/32
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/287

These entries suggest that the issue may be caused by WeChat and/or Line themselves rather than my plugin. [According to this entry](https://stackoverflow.com/questions/30484800/cannot-share-images-to-wechat-and-line-using-action-send-intent), on the other hand, it seems possible to share on WeChat and/or Line but it will limit the usability of the plugin in the following ways:

- it will no longer work on Android API 24 and above
- AFAIK, using setPackage() function will remove all applications from the share menu except WeChat and/or Line

So, until me or someone else figures out a way to fix this issue, I'll mark this issue unsolvable.
